### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by jwnys** [maichmueller/scmodels#5]
The plots contain a network outside of the frame.
In jupyter notebook, the following happens:

```python
myscm.plot(node_size=1000, alpha=1)
```

![image](https://user-images.githubusercontent.com/17109783/104447867-aebfda00-559c-11eb-907b-3f8e5cd5d264.png)

![image](https://user-images.githubusercontent.com/17109783/104447902-bc755f80-559c-11eb-9c5c-ddb5dc3e1ae5.png)

**Comment by maichmueller** [comment]
Thanks for reporting @jwnys. Just found the reason for the bug and going to include it in the 0.2 version release in a few days.
